package com.ifcolab.estetify.view;

import com.ifcolab.estetify.controller.AutenticacaoController;
import javax.swing.JOptionPane;

/**
 *
 * @author vitorsrgio
 */
public class DlgEsqueceuSenha extends javax.swing.JDialog {

    private final AutenticacaoController autenticacaoController;
    
    public DlgEsqueceuSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Recuperar Senha");
        autenticacaoController = new AutenticacaoController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtEmail = new com.ifcolab.estetify.components.CustomTextField();
        btnRecuperar = new com.ifcolab.estetify.components.PrimaryCustomButton();
        btnCancelar = new com.ifcolab.estetify.components.SecondaryCustomButton();
        jLabel6 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblDescricaoPontos = new javax.swing.JLabel();
        lblTitutoSidebar = new javax.swing.JLabel();
        lblBackgroundSidebar = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 870));
        setPreferredSize(new java.awt.Dimension(1350, 870));
        getContentPane().setLayout(null);

        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(edtEmail);
        edtEmail.setBounds(890, 340, 360, 40);

        btnRecuperar.setText("Recuperar Conta");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecuperar);
        btnRecuperar.setBounds(980, 420, 200, 30);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(980, 470, 200, 30);

        jLabel6.setFont(new java.awt.Font("Fira Sans", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("E-mail");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(900, 320, 110, 16);

        lblTitulo.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("<html>Comece a aproveitar as ferramentas<br>de gestão da Estetify<html>");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(70, 250, 640, 88);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo100x88.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(60, 110, 100, 90);

        lblDescricao.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lblDescricao.setText("<html>Ao fazer login, você pode acessar todas as funcionalidades para gerenciar<br>sua clínica de estética em um só lugar. <b>Organize consultas</b>, acompanhe <br><b>históricos</b> de <b>procedimentos</b> e obtenha <b>feedback</b> dos pacientes, tudo<br>com <b>praticidade</b> e <b>segurança</b>.</html>");
        getContentPane().add(lblDescricao);
        lblDescricao.setBounds(70, 360, 660, 120);

        lblDescricaoPontos.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        lblDescricaoPontos.setForeground(new java.awt.Color(0, 0, 0));
        lblDescricaoPontos.setText("<html>Nossas ferramentas ajudam você a:<br> <li>Ganhar tempo ao organizar sua agenda de consultas e procedimentos de maneira centralizada.</li> <li>Acompanhar o histórico de tratamentos e preferências de cada paciente.</li> <li>Receber feedback e obter insights valiosos para aprimorar a experiência dos seus pacientes.</li></html>");
        getContentPane().add(lblDescricaoPontos);
        lblDescricaoPontos.setBounds(70, 490, 630, 160);

        lblTitutoSidebar.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        lblTitutoSidebar.setForeground(new java.awt.Color(0, 0, 0));
        lblTitutoSidebar.setText("Recupere sua senha fornecendo seu e-mail");
        getContentPane().add(lblTitutoSidebar);
        lblTitutoSidebar.setBounds(890, 270, 380, 20);

        lblBackgroundSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sidebar.png"))); // NOI18N
        getContentPane().add(lblBackgroundSidebar);
        lblBackgroundSidebar.setBounds(710, 0, 660, 880);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        lblBackground.setText("jLabel3");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1350, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String email = edtEmail.getText().trim();
            
            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, digite seu email!");
                return;
            }
           
            autenticacaoController.recuperarSenha(email);
            
            JOptionPane.showMessageDialog(this, 
                "Uma nova senha temporária foi enviada para seu email!\n" +
                "Por favor, verifique sua caixa de entrada.");
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao recuperar senha: " + ex.getMessage());
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.SecondaryCustomButton btnCancelar;
    private com.ifcolab.estetify.components.PrimaryCustomButton btnRecuperar;
    private com.ifcolab.estetify.components.CustomTextField edtEmail;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundSidebar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoPontos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitutoSidebar;
    // End of variables declaration//GEN-END:variables
}
