package com.ifcolab.estetify.view;

import com.ifcolab.estetify.controller.FeedbackController;
import javax.swing.JOptionPane;


public class DlgFeedback extends javax.swing.JDialog {
    
    private final FeedbackController controller;

    public DlgFeedback(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new FeedbackController();
        
        btnExcluir.setVisible(controller.isUserAdmin());
        
        btnExcluir.addActionListener((java.awt.event.ActionEvent evt) -> {
            deletarFeedbackSelecionado();
        });

        controller.atualizarTabelaTodosFeedbacks(grdFeedbacks);
    }
    
    private void deletarFeedbackSelecionado() {
        int selectedRow = grdFeedbacks.getSelectedRow();
        if (selectedRow != -1) {
            int opcao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir este feedback?",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            
            if (opcao == JOptionPane.YES_OPTION) {
                try {
                    controller.excluirFeedbackSelecionado(grdFeedbacks, selectedRow);
                    controller.atualizarTabelaTodosFeedbacks(grdFeedbacks);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, 
                        ex.getMessage(),
                        "Erro ao excluir feedback",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                "Selecione um feedback para excluir",
                "Nenhum feedback selecionado",
                JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtituloGerenciaMedicos = new javax.swing.JLabel();
        btnExcluir = new com.ifcolab.estetify.components.PrimaryCustomButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grdFeedbacks = new com.ifcolab.estetify.components.CustomTable();
        pnlBackground = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 870));
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo100x88.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(40, 10, 100, 90);

        lblTitulo.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Feedbacks");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(140, 20, 230, 50);

        lblSubtituloGerenciaMedicos.setFont(new java.awt.Font("Fira Sans Medium", 0, 13)); // NOI18N
        lblSubtituloGerenciaMedicos.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloGerenciaMedicos.setText("Visualize todos os feedbacks dos pacientes.");
        getContentPane().add(lblSubtituloGerenciaMedicos);
        lblSubtituloGerenciaMedicos.setBounds(140, 60, 500, 17);

        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(1140, 60, 190, 30);

        grdFeedbacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(grdFeedbacks);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 120, 1290, 700);

        pnlBackground.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(20, 110, 1310, 720);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        lblBackground.setText("jLabel3");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1350, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.PrimaryCustomButton btnExcluir;
    private com.ifcolab.estetify.components.CustomTable grdFeedbacks;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubtituloGerenciaMedicos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
