package com.ifcolab.estetify.view;

import com.ifcolab.estetify.controller.RelatorioController;
import com.ifcolab.estetify.model.Consulta;
import com.ifcolab.estetify.model.Procedimento;
import javax.swing.JOptionPane;


public class DlgRelatorio extends javax.swing.JDialog {

    private final Consulta consulta;
    private final Procedimento procedimento;
    private final RelatorioController controller;
    private boolean relatorioSalvo = false;
    
    
    public DlgRelatorio(java.awt.Frame parent, boolean modal, Consulta consulta, Procedimento procedimento) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.consulta = consulta;
        this.procedimento = procedimento;
        this.controller = new RelatorioController();
        configurarComponentes();
    }
    
    private void configurarComponentes() {
        // Preencher informações do procedimento
        lblProcedimento.setText("Procedimento: " + procedimento.getTipo());
        lblPaciente.setText("Paciente: " + consulta.getPaciente().getNome());
        lblMedico.setText("Médico: Dr(a). " + consulta.getMedico().getNome());
        lblData.setText("Data: " + consulta.getDataHora().format(
            java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")));
            
        // Configurar área de texto
        txtResultado.setLineWrap(true);
        txtResultado.setWrapStyleWord(true);
        txtObservacoes.setLineWrap(true);
        txtObservacoes.setWrapStyleWord(true);
    }
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcedimento = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnSalvar = new com.ifcolab.estetify.components.PrimaryCustomButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new com.ifcolab.estetify.components.CustomTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new com.ifcolab.estetify.components.CustomTextArea();
        tmRecepcionistas = new javax.swing.JScrollPane();
        grdRecepcionistas = new com.ifcolab.estetify.components.CustomTable();
        lblSubtituloGerenciaMedicos = new javax.swing.JLabel();
        lblTitleGerenciaMedicos = new javax.swing.JLabel();
        lblBackgroundTabela = new javax.swing.JLabel();
        lblBackgroundCadastro = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 870));
        getContentPane().setLayout(null);

        lblProcedimento.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblProcedimento);
        lblProcedimento.setBounds(70, 90, 850, 20);

        lblObservacoes.setForeground(new java.awt.Color(51, 51, 51));
        lblObservacoes.setText("Observações");
        getContentPane().add(lblObservacoes);
        lblObservacoes.setBounds(700, 370, 160, 20);

        lblPaciente.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblPaciente);
        lblPaciente.setBounds(70, 130, 820, 20);

        lblMedico.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblMedico);
        lblMedico.setBounds(70, 180, 660, 20);

        lblData.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblData);
        lblData.setBounds(70, 230, 960, 20);

        lblResultado.setForeground(new java.awt.Color(51, 51, 51));
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(70, 370, 160, 20);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(50, 298, 180, 30);

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(690, 390, 590, 390);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 390, 590, 390);

        grdRecepcionistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tmRecepcionistas.setViewportView(grdRecepcionistas);

        getContentPane().add(tmRecepcionistas);
        tmRecepcionistas.setBounds(40, 366, 1260, 420);

        lblSubtituloGerenciaMedicos.setFont(new java.awt.Font("Fira Sans Medium", 0, 13)); // NOI18N
        lblSubtituloGerenciaMedicos.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloGerenciaMedicos.setText("Organize as informações do procedimento, adicionando resultados e observações");
        getContentPane().add(lblSubtituloGerenciaMedicos);
        lblSubtituloGerenciaMedicos.setBounds(30, 40, 650, 17);

        lblTitleGerenciaMedicos.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        lblTitleGerenciaMedicos.setForeground(new java.awt.Color(51, 51, 51));
        lblTitleGerenciaMedicos.setText("Cadastrar Relatorio");
        getContentPane().add(lblTitleGerenciaMedicos);
        lblTitleGerenciaMedicos.setBounds(30, 20, 210, 22);

        lblBackgroundTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundTableModel.png"))); // NOI18N
        getContentPane().add(lblBackgroundTabela);
        lblBackgroundTabela.setBounds(-10, 330, 1350, 500);

        lblBackgroundCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundCrud.png"))); // NOI18N
        getContentPane().add(lblBackgroundCadastro);
        lblBackgroundCadastro.setBounds(-10, 60, 1330, 290);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        lblBackground.setText("jLabel3");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1350, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            String resultado = txtResultado.getText().trim();
            String observacoes = txtObservacoes.getText().trim();
            
            // Validar campos obrigatórios
            if (resultado.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "O campo Resultado é obrigatório!",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
                txtResultado.requestFocus();
                return;
            }
            
            controller.cadastrar(resultado, observacoes, consulta, procedimento);
            
            relatorioSalvo = true;
            JOptionPane.showMessageDialog(this,
                "Relatório salvo com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao salvar relatório: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    public boolean isRelatorioSalvo() {
        return relatorioSalvo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.PrimaryCustomButton btnSalvar;
    private com.ifcolab.estetify.components.CustomTable grdRecepcionistas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundCadastro;
    private javax.swing.JLabel lblBackgroundTabela;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblProcedimento;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSubtituloGerenciaMedicos;
    private javax.swing.JLabel lblTitleGerenciaMedicos;
    private javax.swing.JScrollPane tmRecepcionistas;
    private com.ifcolab.estetify.components.CustomTextArea txtObservacoes;
    private com.ifcolab.estetify.components.CustomTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
