/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifcolab.estetify.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrAutenticacao extends javax.swing.JFrame {

    /**
     * Creates new form FrAutenticacao
     */
    public FrAutenticacao() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEsqueciSenha = new javax.swing.JLabel();
        txtEmail = new com.ifcolab.estetify.components.CustomTextField();
        pwdSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();
        btnAcessar = new com.ifcolab.estetify.components.PrimaryButton.PrimaryCustomButton();
        lblSidebarWhite = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo100x88.png"))); // NOI18N
        lblLogo.setText("jLabel1");
        getContentPane().add(lblLogo);
        lblLogo.setBounds(30, 80, 100, 90);
        lblLogo.getAccessibleContext().setAccessibleName("");

        lblTitulo.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("<html>Login<html>");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(50, 210, 340, 47);

        lblSubtitle.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtitle.setText("<html>Informe os dados de acesso nos campos abaixo<html>");
        getContentPane().add(lblSubtitle);
        lblSubtitle.setBounds(50, 240, 400, 44);

        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Email:");
        getContentPane().add(lblNome);
        lblNome.setBounds(50, 340, 70, 16);

        lblEsqueciSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblEsqueciSenha.setText("<HTML><u>Esqueci minha senha</u></HTML>");
        lblEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEsqueciSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(lblEsqueciSenha);
        lblEsqueciSenha.setBounds(50, 570, 160, 16);

        txtEmail.setText("Insira seu nome");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(50, 370, 470, 39);

        pwdSenha.setBackground(new java.awt.Color(255, 255, 255));
        pwdSenha.setForeground(new java.awt.Color(111, 111, 111));
        pwdSenha.setText("jPasswordField1");
        pwdSenha.setSelectionEnd(16);
        pwdSenha.setSelectionStart(16);
        getContentPane().add(pwdSenha);
        pwdSenha.setBounds(50, 490, 470, 40);

        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(50, 460, 70, 16);

        btnAcessar.setText(" Acessar");
        getContentPane().add(btnAcessar);
        btnAcessar.setBounds(190, 620, 150, 30);

        lblSidebarWhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sidebar.png"))); // NOI18N
        getContentPane().add(lblSidebarWhite);
        lblSidebarWhite.setBounds(-50, 0, 690, 1020);

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1440, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEsqueciSenhaMouseClicked
            JOptionPane.showMessageDialog(null,"Foi enviado um codigo de verificacao para o email digitado", "Esqueci minha senha", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblEsqueciSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAutenticacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrAutenticacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.PrimaryButton.PrimaryCustomButton btnAcessar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEsqueciSenha;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSidebarWhite;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField pwdSenha;
    private com.ifcolab.estetify.components.CustomTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
