/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifcolab.estetify.view;

/**
 *
 * @author vitorsrgio
 */
public class FrCadastroMedico extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    public FrCadastroMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        primaryCustomButton2 = new com.ifcolab.estetify.components.PrimaryCustomButton();
        secondaryCustomButton2 = new com.ifcolab.estetify.components.SecondaryCustomButton();
        secondaryCustomButton3 = new com.ifcolab.estetify.components.SecondaryCustomButton();
        sidebarCustomButton2 = new com.ifcolab.estetify.components.SidebarCustomButton();
        customTextField3 = new com.ifcolab.estetify.components.CustomTextField();
        customTextField2 = new com.ifcolab.estetify.components.CustomTextField();
        customTextField1 = new com.ifcolab.estetify.components.CustomTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        customTable1 = new com.ifcolab.estetify.components.CustomTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSidebar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setResizable(false);
        getContentPane().setLayout(null);

        primaryCustomButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addsquare.png"))); // NOI18N
        primaryCustomButton2.setText(" Adicionar");
        getContentPane().add(primaryCustomButton2);
        primaryCustomButton2.setBounds(373, 110, 150, 30);

        secondaryCustomButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editsquare.png"))); // NOI18N
        secondaryCustomButton2.setText(" Editar");
        getContentPane().add(secondaryCustomButton2);
        secondaryCustomButton2.setBounds(540, 110, 150, 30);

        secondaryCustomButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        secondaryCustomButton3.setText(" Remover");
        getContentPane().add(secondaryCustomButton3);
        secondaryCustomButton3.setBounds(700, 110, 150, 30);

        sidebarCustomButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        sidebarCustomButton2.setText(" Página principal");
        getContentPane().add(sidebarCustomButton2);
        sidebarCustomButton2.setBounds(10, 130, 210, 46);

        customTextField3.setText("Especialidades");
        customTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(customTextField3);
        customTextField3.setBounds(880, 170, 180, 38);

        customTextField2.setText("CRM");
        customTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(customTextField2);
        customTextField2.setBounds(690, 170, 180, 38);

        customTextField1.setText("Nome");
        customTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(customTextField1);
        customTextField1.setBounds(370, 170, 310, 38);

        customTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(customTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 380, 1010, 560);

        jLabel6.setFont(new java.awt.Font("Fira Sans Medium", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estetify");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 20, 120, 40);

        jLabel5.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo45x40.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 20, 50, 40);

        jLabel1.setFont(new java.awt.Font("Fira Sans Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gerenciar médicos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 40, 160, 20);

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Aqui você pode criar, visualizar e fazer o que quiser meu irmão.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 60, 510, 20);

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SidebarProjeto.png"))); // NOI18N
        getContentPane().add(lblSidebar);
        lblSidebar.setBounds(0, 0, 280, 1020);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundCadastro.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 80, 1100, 290);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundCadastroLista.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 340, 1100, 620);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1440, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField1ActionPerformed

    private void customTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField2ActionPerformed

    private void customTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.CustomTable customTable1;
    private com.ifcolab.estetify.components.CustomTextField customTextField1;
    private com.ifcolab.estetify.components.CustomTextField customTextField2;
    private com.ifcolab.estetify.components.CustomTextField customTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblSidebar;
    private com.ifcolab.estetify.components.PrimaryCustomButton primaryCustomButton2;
    private com.ifcolab.estetify.components.SecondaryCustomButton secondaryCustomButton2;
    private com.ifcolab.estetify.components.SecondaryCustomButton secondaryCustomButton3;
    private com.ifcolab.estetify.components.SidebarCustomButton sidebarCustomButton2;
    // End of variables declaration//GEN-END:variables
}
