/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifcolab.estetify.view;

/**
 *
 * @author vitorsrgio
 */
public class FrMarcarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    public FrMarcarConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnPaginaInicial = new com.ifcolab.estetify.components.SidebarCustomButton();
        lblObservacao = new javax.swing.JLabel();
        lblPaciente = new javax.swing.JLabel();
        lblProcedimento = new javax.swing.JLabel();
        lblEnfermeira = new javax.swing.JLabel();
        lblMedico = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        primaryCustomButton1 = new com.ifcolab.estetify.components.PrimaryButton.PrimaryCustomButton();
        btnEditar = new com.ifcolab.estetify.components.SecondaryCustomButton();
        btnSalvar = new com.ifcolab.estetify.components.SecondaryCustomButton();
        btnRemover = new com.ifcolab.estetify.components.SecondaryCustomButton();
        customComboBox6 = new com.ifcolab.estetify.components.CustomComboBox();
        customComboBox5 = new com.ifcolab.estetify.components.CustomComboBox();
        customComboBox4 = new com.ifcolab.estetify.components.CustomComboBox();
        customComboBox1 = new com.ifcolab.estetify.components.CustomComboBox();
        edtObservacoes = new com.ifcolab.estetify.components.CustomTextField();
        btnAgenda = new com.ifcolab.estetify.components.SidebarCustomButton();
        lblLogoText = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBackgroundCadastroTable = new javax.swing.JLabel();
        lblSidebar = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setResizable(false);
        getContentPane().setLayout(null);

        btnPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnPaginaInicial.setText(" Página principal");
        getContentPane().add(btnPaginaInicial);
        btnPaginaInicial.setBounds(10, 130, 210, 46);

        lblObservacao.setForeground(new java.awt.Color(51, 51, 51));
        lblObservacao.setText("Observações");
        getContentPane().add(lblObservacao);
        lblObservacao.setBounds(950, 230, 130, 17);

        lblPaciente.setForeground(new java.awt.Color(51, 51, 51));
        lblPaciente.setText("Paciente");
        getContentPane().add(lblPaciente);
        lblPaciente.setBounds(380, 150, 130, 17);

        lblProcedimento.setForeground(new java.awt.Color(51, 51, 51));
        lblProcedimento.setText("Procedimento");
        getContentPane().add(lblProcedimento);
        lblProcedimento.setBounds(380, 230, 130, 17);

        lblEnfermeira.setForeground(new java.awt.Color(51, 51, 51));
        lblEnfermeira.setText("Enfermeira");
        getContentPane().add(lblEnfermeira);
        lblEnfermeira.setBounds(1030, 150, 130, 17);

        lblMedico.setForeground(new java.awt.Color(51, 51, 51));
        lblMedico.setText("Médico");
        getContentPane().add(lblMedico);
        lblMedico.setBounds(710, 150, 130, 17);

        lblData.setForeground(new java.awt.Color(51, 51, 51));
        lblData.setText("Data");
        getContentPane().add(lblData);
        lblData.setBounds(710, 230, 130, 17);

        primaryCustomButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addsquare.png"))); // NOI18N
        primaryCustomButton1.setText(" Adicionar");
        getContentPane().add(primaryCustomButton1);
        primaryCustomButton1.setBounds(370, 110, 150, 30);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editsquare.png"))); // NOI18N
        btnEditar.setText(" Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(540, 110, 150, 30);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        btnSalvar.setText(" Remover");
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(710, 110, 150, 30);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnRemover.setText(" Salvar");
        getContentPane().add(btnRemover);
        btnRemover.setBounds(880, 110, 150, 30);
        getContentPane().add(customComboBox6);
        customComboBox6.setBounds(360, 250, 310, 44);
        getContentPane().add(customComboBox5);
        customComboBox5.setBounds(360, 170, 310, 44);
        getContentPane().add(customComboBox4);
        customComboBox4.setBounds(1020, 170, 310, 44);
        getContentPane().add(customComboBox1);
        customComboBox1.setBounds(690, 170, 310, 44);

        edtObservacoes.setText("Observações");
        getContentPane().add(edtObservacoes);
        edtObservacoes.setBounds(940, 250, 390, 38);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar.png"))); // NOI18N
        btnAgenda.setText(" Agendar");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgenda);
        btnAgenda.setBounds(10, 180, 210, 50);

        lblLogoText.setFont(new java.awt.Font("Fira Sans Medium", 0, 24)); // NOI18N
        lblLogoText.setForeground(new java.awt.Color(0, 0, 0));
        lblLogoText.setText("Estetify");
        getContentPane().add(lblLogoText);
        lblLogoText.setBounds(60, 20, 120, 40);

        lblLogo.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(0, 0, 0));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo45x40.png"))); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(10, 20, 50, 40);

        lblTitulo.setFont(new java.awt.Font("Fira Sans Medium", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Marcar Consulta");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(330, 40, 250, 20);

        lblSubtitulo.setForeground(new java.awt.Color(153, 153, 153));
        lblSubtitulo.setText("Aqui você pode criar, visualizar e fazer o que quiser meu irmão.");
        getContentPane().add(lblSubtitulo);
        lblSubtitulo.setBounds(330, 60, 510, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundCadastro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 70, 1120, 290);

        lblBackgroundCadastroTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackgroundCadastroLista.png"))); // NOI18N
        getContentPane().add(lblBackgroundCadastroTable);
        lblBackgroundCadastroTable.setBounds(290, 340, 1100, 620);

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SidebarProjeto.png"))); // NOI18N
        getContentPane().add(lblSidebar);
        lblSidebar.setBounds(0, 0, 280, 1020);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1440, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMarcarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMarcarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.estetify.components.SidebarCustomButton btnAgenda;
    private com.ifcolab.estetify.components.SecondaryCustomButton btnEditar;
    private com.ifcolab.estetify.components.SidebarCustomButton btnPaginaInicial;
    private com.ifcolab.estetify.components.SecondaryCustomButton btnRemover;
    private com.ifcolab.estetify.components.SecondaryCustomButton btnSalvar;
    private com.ifcolab.estetify.components.CustomComboBox customComboBox1;
    private com.ifcolab.estetify.components.CustomComboBox customComboBox4;
    private com.ifcolab.estetify.components.CustomComboBox customComboBox5;
    private com.ifcolab.estetify.components.CustomComboBox customComboBox6;
    private com.ifcolab.estetify.components.CustomTextField edtObservacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundCadastroTable;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEnfermeira;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoText;
    private javax.swing.JLabel lblMedico;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblProcedimento;
    private javax.swing.JLabel lblSidebar;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private com.ifcolab.estetify.components.PrimaryButton.PrimaryCustomButton primaryCustomButton1;
    // End of variables declaration//GEN-END:variables
}
